/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Credentials: () => import('#controllers/credentials_controller'),
  Logs: () => import('#controllers/logs_controller'),
  TwoFactor: () => import('#controllers/two_factor_controller'),
  Users: () => import('#controllers/users_controller'),
}
