/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CredentialSchema extends BaseModel {
  static $columns = [
    'companyId',
    'createdAt',
    'id',
    'notas',
    'passwordEncrypted',
    'servicio',
    'updatedAt',
    'url',
    'userId',
    'username',
  ] as const
  $columns = CredentialSchema.$columns
  @column()
  declare companyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notas: string | null
  @column()
  declare passwordEncrypted: string
  @column()
  declare servicio: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string | null
  @column()
  declare userId: number
  @column()
  declare username: string
}

export class LogSchema extends BaseModel {
  static $columns = [
    'action',
    'createdAt',
    'id',
    'ipAddress',
    'metadata',
    'userAgent',
    'userId',
  ] as const
  $columns = LogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
}

export class RefreshTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'userId'] as const
  $columns = RefreshTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'apellido',
    'companyId',
    'createdAt',
    'email',
    'id',
    'nombre',
    'password',
    'role',
    'twoFactorEnabled',
    'twoFactorSecret',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare apellido: string
  @column()
  declare companyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare twoFactorEnabled: boolean
  @column()
  declare twoFactorSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
