/** Acciones registradas en la tabla `logs` (auditoría). */
export const AuditAction = {
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  CREATE_CREDENTIAL: 'CREATE_CREDENTIAL',
  UPDATE_CREDENTIAL: 'UPDATE_CREDENTIAL',
  DELETE_CREDENTIAL: 'DELETE_CREDENTIAL',
  VIEW_CREDENTIALS: 'VIEW_CREDENTIALS',
  VIEW_EQUIPOS: 'VIEW_EQUIPOS',
  CREATE_EQUIPO: 'CREATE_EQUIPO',
  UPDATE_EQUIPO: 'UPDATE_EQUIPO',
  DELETE_EQUIPO: 'DELETE_EQUIPO',
  GRANT_EQUIPO_ACCESS: 'GRANT_EQUIPO_ACCESS',
  REVOKE_EQUIPO_ACCESS: 'REVOKE_EQUIPO_ACCESS',
  VIEW_EQUIPO_CREDENTIALS: 'VIEW_EQUIPO_CREDENTIALS',
  CREATE_EQUIPO_CREDENTIAL: 'CREATE_EQUIPO_CREDENTIAL',
  UPDATE_EQUIPO_CREDENTIAL: 'UPDATE_EQUIPO_CREDENTIAL',
  DELETE_EQUIPO_CREDENTIAL: 'DELETE_EQUIPO_CREDENTIAL',
  MIGRATION_CREDENTIAL_TO_EQUIPO: 'MIGRATION_CREDENTIAL_TO_EQUIPO',
} as const

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction]
